

## Day Objectives

- Python Libraries for Data Science
    - Numpy


### Numpy Library

- Processing N-Dimensional Arrays

In [5]:
import numpy as np

li =[1,2,3]

a = np.array(li) ## Converts the list into array. Array must contain only homogeneous elements.

b = np.arange(10) ## Adds 10 elements from 0 to 9 into an array.

b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
## Create array using numpy and random.
random_nums = np.random.randint(0,100,size=10) #one-dimensional array
random_nums = np.random.randint(0,100,size = (2,1)) #Two Dimentional array
random_nums = np.random.randint(0,100,size = (3,3,3,3)) #Three Dimensional array
print(random_nums)
random_nums[0][0][0]
random_nums[2][2][2][2]

[[[[43 27 99]
   [44 97 64]
   [ 2 34 70]]

  [[20 32 65]
   [30 74 21]
   [17 67 97]]

  [[22 53 31]
   [23 51 97]
   [86 45 41]]]


 [[[85 83 28]
   [ 9 55 63]
   [29 87 51]]

  [[65 44  8]
   [69 25 91]
   [51  1 38]]

  [[16  8 65]
   [ 4 89 41]
   [64 89 85]]]


 [[[ 1 35  2]
   [38 49 46]
   [19 91 35]]

  [[79 29 84]
   [93 81 11]
   [32 71 19]]

  [[14  1 71]
   [97 79 12]
   [74 35 13]]]]


13

In [32]:
random_nums.ndim ## returns the no.of dimensions of an array.

4

In [33]:
random_nums.size ## returns no.of elements in an array

108

In [35]:
li = [1,2,3,4,5]
li[-2:]

[4, 5]

In [47]:
random_nums.dtype ## returns type of data

dtype('int32')

In [52]:
li = [1,2,3,4,5,6,7,8,9]
a = np.array(li)
print(a)
a.reshape(3,3)

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
m = np.ones((4,4))
m

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])